apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmarking-k8s-worker
  namespace: bench-k8s
  labels:
    app: benchmarking-k8s-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: benchmarking-k8s-worker
  template:
    metadata:
      labels:
        app: benchmarking-k8s-worker
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-node
      containers:
      - name: matrix-multiplication
        image: ovuncertunc/matrix_multiplication_amd
        securityContext:
          privileged: true
        env:
        - name: MATRIX_SIZE
          value: "10"
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "500m"