apiVersion: v1
kind: Service
metadata:
  name: benchmarking-k8s-service
  namespace: bench-k8s
  labels:
    app: benchmarking-k8s-worker
spec:
  selector:
    app: benchmarking-k8s-worker
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http